import React,{useEffect,useState} from 'react' 
import Head from 'next/head'
import Message from '../components/Message'
import { db } from '../utils/firebase';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Link from 'next/link';

 
export default function Home() {
   const [allPosts,setAllPosts]=useState([]); 
   const collectionRef=collection(db,'posts');
   const q=query(collectionRef,orderBy('timestamp','desc'));
 
   useEffect(()=>{
    onSnapshot(q,snapshot=>{
        setAllPosts(
          snapshot.docs.map(doc=>({
            id:doc.id,
            ...doc.data()
          }))
        )
    })

   },[])

   //console.log(allPosts);
  return (
    <>

      <Head>
        <title>Firebase App 5</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='my-12 text-lg font-medium'>
        <h2 >See what other people are saying </h2>
          {
            allPosts.map( (post,i)=>(
              <Message {...post} key={post.id}>
                <Link href={{pathname:`/${post.id}`, query: {...post}}}>
                  <button>{post.comments?.length ? post.comments?.length: 0 } comments</button>
                </Link>
              </Message> 
            ))
          }
      </div>


    </>
  )
}


 